language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: 10
before_install:
  - "npm install -g bower"
  - bower install web-component-tester  
  - "npm install -g web-component-tester"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success:
  - gulp dist
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
